### ISSUE TITLE
Feature Request: Include nicknames in tracker

### ISSUE THREAD

**Issue by JarredAllen** [diballesteros/nuzlocke#531]
**Is your feature request related to a problem? Please describe.**

No, it is not related to an existing problem.

**Describe the solution you'd like**

Each pokemon should have an extra field in the tracker which allows you to input a nickname.

**Describe alternatives you've considered**

The nickname could be used in other parts of the app (such as the summary page under stats), but just tracking nicknames is a good start (and they can always be added in later). This feature could also not be added, but I know at least one person who won't use this app without this feature (and I personally want it).

**Additional context**

I can write the code for including this feature in the app, if you'd be willing to merge it.

**Comment by diballesteros** [comment]
Hey Jarred, thanks for writing this up! Nicknames are already included as a feature in the app, but you have to turn them on to see them. You can check it out from the settings page by enabling nicknames,

![image](https://user-images.githubusercontent.com/17815139/173236834-80e7f257-3feb-49ef-b558-58038d166299.png)
