### ISSUE TITLE
Make menu into sidebar

### ISSUE THREAD

**Issue by diballesteros** [diballesteros/nuzlocke#89]
**Describe the solution you'd like**
Change top left menu into a sidebar that launches from the left using semantic UI component

Split changelog and about section

About section should have credits and call-to-action for playstore and microsoft store

**Comment by RyoMasumura1201** [comment]
I'd like to help this issue and am on it.

**Comment by diballesteros** [comment]
> I'd like to help with this issue and am on it.

Sure thing! Make sure to check out the contributing.md and don't hesitate to message me for any details.
