### ISSUE TITLE
Cypress tests for Smart Rules

### ISSUE THREAD

**Issue by diballesteros** [diballesteros/nuzlocke#93]
Cypress tests for Smart Rules

Should be located in the file Rules.spec.ts

Should test when the rules of generation, level and types are broken and the alert text appears in the Tracker tab

The rules can be configured from the Rules Tab when adding a rule.

Each type of rule is a different tab within the modal.

Generation -> Multiselect
Type -> Multiselect
Level -> Number input

Any generation, type or max level can be tested but test must assert that the text on the entry in the Tracker tab appears when the rule is being broken.

**Comment by RyoMasumura1201** [comment]
I'd like to help with this issue.

**Comment by diballesteros** [comment]
> I'd like to help with this issue.

Sure thing!
